#pragma once
#include <bits/stdc++.h>
using namespace std;
#include "cardinal.hpp"
#include "dijkstra.hpp"
#include "EK.hpp"
#include "fft.hpp"
#include "floyd.hpp"
#include "graph.hpp"
#include "kmp.hpp"
#include "math.hpp"
#include "matrix.hpp"
#include "mfset.hpp"
#include "mint.hpp"
#include "network.hpp"
#include "prime.hpp"
#include "segtree.hpp"
#include "sgttree.hpp"
#include "splay.hpp"